services:
  bot:
    build: .
    container_name: tg-ytaudio-bot-dev
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
      - ./storage/db:/app/storage/db
    environment:
      - PYTHONPATH=/app
      - RESET_DB_ON_START=true
