services:
  bot:
    build: .
    container_name: tg-ytaudio-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage/audio:/storage/audio
      - ./storage/db:/storage/db
    networks:
      - ytaudio_net
    environment:
      - PYTHONPATH=/app
      - YT_PROXY_PRIMARY=socks5://127.0.0.1:1080
      - YT_PROXY_SECONDARY=socks5://127.0.0.1:1081

  nginx:
    image: nginx:alpine
    container_name: tg-ytaudio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./storage/audio:/storage/audio:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - bot
    networks:
      - ytaudio_net

networks:
  ytaudio_net:
